"""A12 (מעקב טכנולוגי, 2026-09-06 user request): weekly technology-watch aggregation.

FR: "לא ראיתי התייחסות להתפתחויות טכנולוגיות — לדוגמה פרסומים מדעיים בנושא FPA עם פיקסל דיגיטלי."
The `tech_dev` domain (config/taxonomy.yaml) and classify.md's tech-watch rule route peer-reviewed
papers, conference proceedings and patents into scope even without a defense customer -- but those
items often score too low on novelty/magnitude/core_relevance (eoa.pipeline.triage) to ever reach
a level-gated report section. This module aggregates them independently of triage level, per
`tech_dev` subdomain, for the weekly report (eoa.report.tech_watch / eoa.report.weekly):

  - ``new_count``: items published/fetched in the period.
  - ``notable_items``: the highest-scoring items in the period (still capped/ordered by `score`,
    just not level-filtered).
  - ``actors``: distinct entities mentioned across the notable items.
  - ``momentum``: this week's count vs. the trailing 4-week average for the same subdomain
    ("up"/"down"/"flat" + a percent delta when the baseline is non-zero).
  - ``so_what_he``: one Hebrew sentence ("מה זה אומר למוצרי EO/IR") generated by the resident LLM,
    grounded only in the subdomain's own notable items (wrapped as DATA per CONVENTIONS.md rule 3)
    -- never fabricated when there is nothing to summarize.

Pure DB + one small LLM call per subdomain; every DB query is read-only and a subdomain with no
activity simply reports zeros rather than raising, so a single bad subdomain never blocks the
weekly report build.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass, field
from typing import Any

import structlog
from pydantic import BaseModel, Field

from eoa.config import settings
from eoa.db import connection
from eoa.errors import LLMOutputError, ResourceUnavailable
from eoa.llm.ollama_client import DATA_GUARD_SYSTEM, chat_structured, wrap_data
from eoa.llm.prompts import render

log = structlog.get_logger(__name__)

DOMAIN = "tech_dev"
NOTABLE_PER_SUBDOMAIN = 5
MOMENTUM_WEEKS = 4
_MOMENTUM_THRESHOLD_PCT = 15.0


class TechSoWhatOut(BaseModel):
    """Stage: tech_watch so-what (resident model, one call per subdomain)."""

    so_what_he: str = Field(description="משפט אחד-שניים בעברית, חייב להתחיל ב'להערכתנו'")


@dataclass
class SubdomainAggregate:
    subdomain: str
    label_he: str
    new_count: int
    notable_items: list[dict[str, Any]] = field(default_factory=list)
    actors: list[str] = field(default_factory=list)
    momentum: str = "flat"  # "up" | "down" | "flat"
    momentum_delta_pct: float | None = None
    so_what_he: str = ""


def _fetchall(sql: str, params: dict[str, Any] | None = None) -> list[dict[str, Any]]:
    with connection() as conn, conn.cursor() as cur:
        cur.execute(sql, params or {})
        return cur.fetchall()


def _subdomains() -> dict[str, str]:
    """``{subdomain_key: hebrew_label}`` for the `tech_dev` domain, from config/taxonomy.yaml --
    config, not code (CONVENTIONS.md rule 6), so a taxonomy edit needs no code change here."""
    domains = settings().taxonomy.get("domains", {})
    return dict(domains.get(DOMAIN, {}).get("sub", {}))


def count_in_window(subdomain: str, start: dt.datetime, end: dt.datetime) -> int:
    """Number of clean, non-duplicate `tech_dev`/`subdomain` items in `[start, end)`."""
    rows = _fetchall(
        """
        SELECT count(*) AS n FROM items
        WHERE domain = %(domain)s AND subdomain = %(sub)s
          AND security_status = 'clean' AND dedup_of IS NULL
          AND COALESCE(published_at, fetched_at, created_at) >= %(start)s
          AND COALESCE(published_at, fetched_at, created_at) < %(end)s
        """,
        {"domain": DOMAIN, "sub": subdomain, "start": start, "end": end},
    )
    return rows[0]["n"] if rows else 0


def notable_items(
    subdomain: str, start: dt.datetime, end: dt.datetime, *, limit: int = NOTABLE_PER_SUBDOMAIN
) -> list[dict[str, Any]]:
    """Top-`limit` `tech_dev`/`subdomain` items in the period by score (not level-filtered --
    see module docstring)."""
    return _fetchall(
        """
        SELECT i.id, i.title, i.url, i.published_at, i.score, i.trl, i.tech_maturity,
               i.tech_actor_kind, i.summary_he, i.so_what_he, i.entities_mentioned,
               COALESCE(src.name, i.url) AS source_name
        FROM items i
        LEFT JOIN sources src ON src.id = i.source_id
        WHERE i.domain = %(domain)s AND i.subdomain = %(sub)s
          AND i.security_status = 'clean' AND i.dedup_of IS NULL
          AND COALESCE(i.published_at, i.fetched_at, i.created_at) >= %(start)s
          AND COALESCE(i.published_at, i.fetched_at, i.created_at) < %(end)s
        ORDER BY i.score DESC NULLS LAST, i.published_at DESC NULLS LAST
        LIMIT %(limit)s
        """,
        {"domain": DOMAIN, "sub": subdomain, "start": start, "end": end, "limit": limit},
    )


def _actors(items: list[dict[str, Any]], *, limit: int = 8) -> list[str]:
    seen: list[str] = []
    for it in items:
        for name in it.get("entities_mentioned") or []:
            if name not in seen:
                seen.append(name)
    return seen[:limit]


def compute_momentum(
    subdomain: str, period_end: dt.datetime, *, weeks: int = MOMENTUM_WEEKS
) -> tuple[str, float | None]:
    """This week's (the 7 days ending `period_end`) item count vs. the trailing `weeks`-week
    average for the same subdomain, immediately before that week. Returns
    ``("up"|"down"|"flat", delta_pct_or_None)`` -- ``delta_pct`` is ``None`` when the baseline is
    zero (a brand-new subdomain has no meaningful percent change; "up" is still reported if this
    week has any activity at all, "flat" otherwise)."""
    this_start = period_end - dt.timedelta(days=7)
    this_count = count_in_window(subdomain, this_start, period_end)

    prev_counts = []
    for w in range(weeks):
        w_end = this_start - dt.timedelta(days=7 * w)
        w_start = w_end - dt.timedelta(days=7)
        prev_counts.append(count_in_window(subdomain, w_start, w_end))
    baseline = sum(prev_counts) / len(prev_counts) if prev_counts else 0.0

    if baseline <= 0:
        return ("up", None) if this_count > 0 else ("flat", None)
    delta_pct = ((this_count - baseline) / baseline) * 100
    if delta_pct > _MOMENTUM_THRESHOLD_PCT:
        return "up", delta_pct
    if delta_pct < -_MOMENTUM_THRESHOLD_PCT:
        return "down", delta_pct
    return "flat", delta_pct


def _so_what_system() -> str:
    return render("system_analyst", data_guard=DATA_GUARD_SYSTEM)


def _so_what_prompt(subdomain_label: str, items: list[dict[str, Any]]) -> str:
    bullets = "\n".join(
        f"- [item {it['id']}] {it.get('title') or ''}: "
        f"{it.get('so_what_he') or it.get('summary_he') or ''}"
        for it in items
    )
    return render(
        "tech_watch_so_what",
        subdomain_label=subdomain_label,
        data=wrap_data(bullets, "tech_watch", ""),
    )


def generate_so_what(subdomain_label: str, items: list[dict[str, Any]], *, role: str = "resident") -> str:
    """One resident-model call: "מה זה אומר למוצרי EO/IR" for one subdomain, grounded only in its
    own `items` (empty string, never a call, when there is nothing to summarize)."""
    if not items:
        return ""
    try:
        out = chat_structured(
            role,
            TechSoWhatOut,
            [
                {"role": "system", "content": _so_what_system()},
                {"role": "user", "content": _so_what_prompt(subdomain_label, items)},
            ],
            task="summarize",
            options={"temperature": 0.3},
        )
        return out.so_what_he
    except (ResourceUnavailable, LLMOutputError) as exc:
        log.warning("tech_watch_so_what_failed", subdomain=subdomain_label, error=str(exc)[:160])
        return ""


def run_tech_watch_weekly(
    period_start: dt.datetime, period_end: dt.datetime, *, role: str = "resident"
) -> list[SubdomainAggregate]:
    """One `SubdomainAggregate` per `tech_dev` subdomain in the taxonomy, sorted by `new_count`
    descending. Never raises: a single subdomain's LLM call failing degrades to an empty
    `so_what_he` for that subdomain only (see `generate_so_what`)."""
    results: list[SubdomainAggregate] = []
    for sub_key, label in _subdomains().items():
        items = notable_items(sub_key, period_start, period_end)
        new_count = count_in_window(sub_key, period_start, period_end)
        momentum, delta = compute_momentum(sub_key, period_end)
        so_what = generate_so_what(label, items, role=role)
        results.append(
            SubdomainAggregate(
                subdomain=sub_key,
                label_he=label,
                new_count=new_count,
                notable_items=items,
                actors=_actors(items),
                momentum=momentum,
                momentum_delta_pct=delta,
                so_what_he=so_what,
            )
        )
    results.sort(key=lambda r: r.new_count, reverse=True)
    log.info(
        "tech_watch_weekly_done",
        subdomains=len(results),
        total_new=sum(r.new_count for r in results),
    )
    return results
